/Users/michaelbyrne/Downloads/andscacs-921a_src/analisis.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/avaluacio.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/debug.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/definicions.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/es.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/finals.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/hash.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/magics.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/moviments.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/mtwist.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/resource.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/tbconfig.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/tbcore.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/tbprobe.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/temps.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/thread.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/utils.h
/Users/michaelbyrne/Downloads/andscacs-921a_src/varis.h
